### ISSUE TITLE
关于该代码的论文

### ISSUE THREAD

**Issue by YvetteYangg** [RecklessRonan/MuSE#1]
您好，我在搜索多模态NER及MSA相关代码时查找到您的代码仓库，但因为没有模型的架构说明，感觉理解起来比较吃力，请问本代码仓库是否有已发表或形成的相关论文呢？如有，还希望您能附上论文的相关地址，以便理解学习，万分感谢！

**Comment by RecklessRonan** [comment]
谢谢你的关注~我们这篇论文正在投稿中，还不方便公开。也请暂时不要fork和参考~
